### PR TITLE
[Azure] Add sovereign cloud support for Resource Group

### LINKED ISSUE #859: [Azure] Add sovereign cloud support for resource group
The Base URI is incorrectly resolved for the resource group client, and should be fixed to read from the environment.

Addresses #811

### PR DESCRIPTION
**Pull request by davidkpiano**
This PR resolves the Base URI for the Resource Group module to support sovereign cloud.

Addresses #811, fixes #859

cc. @rguthriemsft

### CODE REVIEW

**Comment by hattan** [comment]
[Microsoft CI Bot] TL;DR; failure :facepalm:

You can check the status of the CI Pipeline logs here ; https://github.com/aztfmod/terratest/actions/runs/741664244

**Comment by hattan** [comment]
[Microsoft CI Bot] TL;DR; success :thumbsup:

You can check the status of the CI Pipeline logs here ; https://github.com/aztfmod/terratest/actions/runs/755898427

**Review by HadwaAbdelhalem — DISMISSED** [review]
LGTM, @gruntwork-terratest-terragrunt ready for review

**Comment by yorinasub17** [comment]
NOTE: Looks like there is a merge conflict now that we merged some of the other PRs.

**Review by HadwaAbdelhalem — APPROVED** [review]
LGMT, @yorinasub17 conflicts resolved. Ready for your review

**Comment by davidkpiano** [comment]
Superseded by #884

**Pull request closed without merging**
