### PR TITLE
Update Terratest to work with Terraform 0.14

### LINKED ISSUE #717: TF 0.14.0 String Output leaves double quotes
Using `v0.30.27`. Having a simple tf `v0.14.0` code:

```
output "hello_world" {
  value = "Hello, World!"
}
```

Trying to:

```
output := terraform.Output(t, terraformOptions, "hello_world")
assert.Equal(t, "Hello, World!", output)
```

Fails with:

```
                Error:          Not equal: 
                                expected: "Hello, World!"
                                actual  : "\"Hello, World!\""
                            
                                Diff:
                                --- Expected
                                +++ Actual
                                @@ -1 +1 @@
                                -Hello, World!
                                +"Hello, World!"
```

### PR DESCRIPTION
**Pull request by brikis98**
Fixes #717. Built on @dee-kryvenko's work in #718.

Fixes:

1. Bump CI to 0.14.
1. Fix `terraform.Output` to use `-json`, as the non `-json` version had backwards incompatible changes.
1. Fix Terraform formatting / syntax. The `terraform fmt` command caught some broken syntax... Not sure how that worked before?

### CODE REVIEW

**Comment by brikis98** [comment]
A couple tests failed, but they are flaky tests that are unrelated to this PR.

**Review by ina-stoyanova — APPROVED** [review]
Looks good! 👍 Noted about the tests - are they intermittent? Is it worth raising an issue just yet for them?

**Comment by brikis98** [comment]
> Is it worth raising an issue just yet for them?

Good idea. Filed https://github.com/gruntwork-io/terratest/issues/720.

Thanks for the review! Merging now.

**Comment by brikis98** [comment]
https://github.com/gruntwork-io/terratest/releases/tag/v0.31.0

**Comment by Avanishkumar28** [comment]
Hi @brikis98 

Is there any action I need to take to point this branch on my local system?

**Comment by dee-kryvenko** [comment]
@Avanishkumar28 `v0.31.0` has been already released, I just tested it and it works now. Do `go get -u github.com/gruntwork-io/terratest`.

**Comment by Avanishkumar28** [comment]
Hi @dee-kryvenko 
Thanks for quick reply, after `go get -u github.com/gruntwork-io/terratest` it start working but 
I got another error 
`Error:          
          Error Trace:    output.go:17
          Error:              Received unexpected error:
                                json: cannot unmarshal bool into Go value of type string`

**Comment by Avanishkumar28** [comment]
Terraform output:
`TestRDSAurora 2020-12-04T22:47:57+05:30 logger.go:66: rds_cluster_instance_publicly_accessible = [
TestRDSAurora 2020-12-04T22:47:57+05:30 logger.go:66:   false,
TestRDSAurora 2020-12-04T22:47:57+05:30 logger.go:66:   false,
TestRDSAurora 2020-12-04T22:47:57+05:30 logger.go:66:   false,
TestRDSAurora 2020-12-04T22:47:57+05:30 logger.go:66: ]
`

**Comment by dee-kryvenko** [comment]
@Avanishkumar28 seems like I broke backward compatibility, sorry about that. It wasn't clear this function was supposed to handle anything other than strings and it didn't had any tests. I am working on another PR to fix that. Meantime you can temporary use `OutputStruct`:

```go
	var o interface{}
	terraform.OutputStruct(t, terraformOptions, "hello_world", &o)
	assert.Equal(t, "Hello, World!", fmt.Sprintf("%v", o))
```

Or

```go
	var b bool
	terraform.OutputStruct(t, terraformOptions, "hello_world", &b)
	assert.Equal(t, true, b)
```

@brikis98 @ina-stoyanova would you be so kind please https://github.com/gruntwork-io/terratest/pull/723

**Pull request merged**
