### PR TITLE
Feature/issue 1260

### PR DESCRIPTION
**Pull request by marcellmartini**
## Description

This PR implements the enhancement proposed in [issue #1260](https://github.com/gruntwork-io/terratest/issues/1260)

## TODOs

Read the [Gruntwork contribution guidelines](https://gruntwork.notion.site/Gruntwork-Coding-Methodology-02fdcd6e4b004e818553684760bf691e).

- [X] Update the docs.
- [X] Run the relevant tests successfully, including pre-commit checks.
- [X] Ensure any 3rd party code adheres with our [license policy](https://www.notion.so/gruntwork/Gruntwork-licenses-and-open-source-usage-policy-f7dece1f780341c7b69c1763f22b1378) or delete this line if its not applicable.
- [ ] Include release notes. If this PR is backward incompatible, include a migration guide.

## Release Notes (draft)

- [X] Added DeploymentNotAvailable struct.
- [X] Added Deployment functions.
- [X] Updated tunnel. go to support port forwarding for deployment resources.
- [X] Added test related to tunnel support port forwarding for deployment resources.

### Migration Guide

There aren`t backward incompatible changes

### CODE REVIEW

**Comment by marcellmartini** [comment]
Hi, With the modifications I did in this PR those tests in CI supposed to break? Do I have to do something to fix those CI fails?

**Comment by zackproser** [comment]
Hi @marcellmartini - thanks so much for your PR and contribution - we're getting this queued up for review!

**Comment by denis256** [comment]
Failed tests aren't related to added changes

**Comment by marcellmartini** [comment]
@zackproser and @denis256 Thank you. I will get other issues to help. Are there any issues you´d like to prioritize?

**Pull request merged**
