### PR TITLE
[azure] Add sovereign cloud support for remaining modules

### PR DESCRIPTION
**Pull request by davidkpiano**

### CODE REVIEW

**Review by HadwaAbdelhalem — DISMISSED** [review]
LGTM. @gruntwork-io/gruntwork-terratest-terragrunt ready for your review

**Review by yorinasub17 — DISMISSED** [review]
LGTM!

**Comment by yorinasub17** [comment]
Will run a sanity check build to make sure the precommit hooks pass, and then merge this in!

**Comment by yorinasub17** [comment]
Hmm our circleci build failed with the following compilation error:

```
# github.com/gruntwork-io/terratest/modules/azure [github.com/gruntwork-io/terratest/modules/azure.test]
modules/azure/actiongroup.go:42:9: cannot use &actionGroup (type *"github.com/Azure/azure-sdk-for-go/services/preview/monitor/mgmt/2019-06-01/insights".ActionGroupResource) as type *"github.com/Azure/azure-sdk-for-go/services/preview/monitor/mgmt/2018-03-01/insights".ActionGroupResource in return argument
modules/azure/mysql.go:59:9: cannot use &mysqlServer (type *"github.com/Azure/azure-sdk-for-go/services/mysql/mgmt/2020-01-01/mysql".Server) as type *"github.com/Azure/azure-sdk-for-go/services/mysql/mgmt/2017-12-01/mysql".Server in return argument
FAIL	github.com/gruntwork-io/terratest/modules/azure [build failed]
FAIL
```

Can you take a look to see what might be up? Not sure if it is related, but our build uses go version 1.14

**Comment by davidkpiano** [comment]
> Hmm our circleci build failed with the following compilation error:
> 
> ```
> # github.com/gruntwork-io/terratest/modules/azure [github.com/gruntwork-io/terratest/modules/azure.test]
> modules/azure/actiongroup.go:42:9: cannot use &actionGroup (type *"github.com/Azure/azure-sdk-for-go/services/preview/monitor/mgmt/2019-06-01/insights".ActionGroupResource) as type *"github.com/Azure/azure-sdk-for-go/services/preview/monitor/mgmt/2018-03-01/insights".ActionGroupResource in return argument
> modules/azure/mysql.go:59:9: cannot use &mysqlServer (type *"github.com/Azure/azure-sdk-for-go/services/mysql/mgmt/2020-01-01/mysql".Server) as type *"github.com/Azure/azure-sdk-for-go/services/mysql/mgmt/2017-12-01/mysql".Server in return argument
> FAIL	github.com/gruntwork-io/terratest/modules/azure [build failed]
> FAIL
> ```
> 
> Can you take a look to see what might be up? Not sure if it is related, but our build uses go version 1.14

Taking a look now.

**Comment by davidkpiano** [comment]
Imports fixed; this should be ready for re-review

**Review by yorinasub17 — APPROVED** [review]
LGTM!

**Comment by skarlupka** [comment]
@davidkpiano !  I recently started getting this error from my CI server

`/home/AzDevOps/go/pkg/mod/github.com/gruntwork-io/terratest@v0.34.4/modules/azure/actiongroup.go:42:9: cannot use &actionGroup (type *"github.com/Azure/azure-sdk-for-go/services/preview/monitor/mgmt/2019-03-01/insights".ActionGroupResource) as type *"github.com/Azure/azure-sdk-for-go/services/preview/monitor/mgmt/2019-06-01/insights".ActionGroupResource in return argument`

I've tried Go 1.13 and 1.14 and run into the same issue. I'm wondering if this is related to this PR?

**Comment by pajcarpentier** [comment]
after this update, I've got the following error in Azure pipeline Go Get task : 

```
"gopath\src\github.com\gruntwork-io\terratest\modules\azure\actiongroup.go:42:9: cannot use &actionGroup (type *"github.com/Azure/azure-sdk-for-go/services/preview/monitor/mgmt/2019-03-01/insights".ActionGroupResource) as type *"github.com/Azure/azure-sdk-for-go/services/preview/monitor/mgmt/2019-11-01-preview/insights".ActionGroupResource in return argument
"
```

**Comment by davidkpiano** [comment]
> Hello all.
> After this update, I've got the following error in Azure pipeline Go Get task :
> 
> ```
> "gopath\src\github.com\gruntwork-io\terratest\modules\azure\actiongroup.go:42:9: cannot use &actionGroup (type *"github.com/Azure/azure-sdk-for-go/services/preview/monitor/mgmt/2019-03-01/insights".ActionGroupResource) as type *"github.com/Azure/azure-sdk-for-go/services/preview/monitor/mgmt/2019-11-01-preview/insights".ActionGroupResource in return argument
> "
> ```
> 
> As the pipeline worked last friday, I suppose there is a connection between :)
> [EDIT] oups... fired by @skarlupka :)
> [Edit2] pipeline has ran on Monday the 26th last time with succes (without this error I mean)

I'm looking into this now.

**Comment by pajcarpentier** [comment]
@Davidpiano : the pipeline failed today.
It ran with success on Monday of April, the 26th.

**Comment by pajcarpentier** [comment]
@davidkpiano : just to confirm that with previous version I did not have the error : 

`        - task: Go@0
          displayName: 'Go modules init for Azure v0.33.0'
          inputs:
            command: mod
            arguments: '$(TF_LOG) init github.com/gruntwork-io/terratest/modules/azure/v0.33.0'
            
        - task: Go@0
          displayName: 'Install Go Terratest Azure module v0.33.0'
          inputs:
            command: get
            arguments: '$(TF_LOG) github.com/gruntwork-io/terratest/modules/azure@v0.33.0'
`

**Comment by yorinasub17** [comment]
Hi @pajcarpentier, you should use `github.com/gruntwork-io/terratest@v0.33.0` instead of ` github.com/gruntwork-io/terratest/modules/azure@v0.33.0`.

The reason for the breakage is that our `go.mod` file is actually located at the root of the repo, not each module folder. By using the specific module folder, `go` is actually ignoring the `go.mod` file located at the root, and is pulling in the latest dependencies that are referenced by the `azure` package instead of the version locked ones we define in the root `go.mod`.

**Pull request merged**
