### PR TITLE
Use ReadLine to be able to work with long lines

### PR DESCRIPTION
**Pull request by tommyknows**
Similar to PR #502, this commit switches from using bufio.Scanner to
bufio.Reader. See #502 for more information.

I hope you don't mind that I changed the massive `if else` chain to a switch-statement - if you do, I'll revert it 🙂 

Signed-off-by: Ramon Rüttimann <me@ramonr.ch>

### CODE REVIEW

**Comment by yorinasub17** [comment]
Looks like a few of the parser unit tests failed due to whitespace differences in the fixtures. E.g., TestBasicExample

**Comment by tommyknows** [comment]
Ah yes, forgot about the newline 🙂 
Should be working now.

**Comment by yorinasub17** [comment]
Thanks for the update! Just kicked off another build.

**Comment by yorinasub17** [comment]
The build failed, but for an unrelated known flaky test so will go ahead and merge this in. Thanks for the contribution!

**Pull request merged**
