### PR TITLE
test: update basic azure example to provider 2.0.0

### PR DESCRIPTION
**Pull request by tsalright**
Updated the **provider azurerm** version to 2.0.0 and added the missing feature {} field. This addresses issue https://github.com/gruntwork-io/terratest/issues/534.

### CODE REVIEW

**Comment by brikis98** [comment]
Please see https://github.com/gruntwork-io/terratest/issues/89 for the status on Terratest with Azure. In particular, we're [starting some work](https://github.com/gruntwork-io/terratest/issues/89#issuecomment-650052374) around it, and when that work is done, we'll be able to come back to this PR!

**Comment by yorinasub17** [comment]
@tsalright Is this PR still necessary or should we close this out? It looks like the version locking was removed when we started testing: https://github.com/gruntwork-io/terratest/blob/master/examples/azure/terraform-azure-example/main.tf

**Comment by rguthriemsft** [comment]
we should close this PR out.  I don't think it is needed anymore.

**Comment by yorinasub17** [comment]
Closing as obsolete. Thanks!

**Pull request closed without merging**
