### PR TITLE
Use azure V46.0.0 compatible references for azure monitor

### LINKED ISSUE #886: azure module go compilation error
Trying to run `go get -v -u github.com/gruntwork-io/terratest/modules/azure` fails. The error is below. This issue started after the release last night. I think `0.34.2` introduced the bug, but it could have been `0.34.1`. I am not confident.

```
/go/src/github.com/gruntwork-io/terratest/modules/azure/monitor.go:59:9: cannot use &settings (type *"github.com/Azure/azure-sdk-for-go/services/preview/monitor/mgmt/2019-11-01-preview/insights".DiagnosticSettingsResource) as type *"github.com/Azure/azure-sdk-for-go/services/preview/monitor/mgmt/2019-06-01/insights".DiagnosticSettingsResource in return argument
/go/src/github.com/gruntwork-io/terratest/modules/azure/monitor.go:103:9: cannot use &status (type *"github.com/Azure/azure-sdk-for-go/services/preview/monitor/mgmt/2019-11-01-preview/insights".VMInsightsOnboardingStatus) as type *"github.com/Azure/azure-sdk-for-go/services/preview/monitor/mgmt/2019-06-01/insights".VMInsightsOnboardingStatus in return argument
/go/src/github.com/gruntwork-io/terratest/modules/azure/monitor.go:156:9: cannot use &activityLogAlertResource (type *"github.com/Azure/azure-sdk-for-go/services/preview/monitor/mgmt/2019-11-01-preview/insights".ActivityLogAlertResource) as type *"github.com/Azure/azure-sdk-for-go/services/preview/monitor/mgmt/2019-06-01/insights".ActivityLogAlertResource in return argument
```

### PR DESCRIPTION
**Pull request by HadwaAbdelhalem**
Fixes #886  and  Closese #886

### CODE REVIEW

**Comment by hattan** [comment]
[Microsoft CI Bot] TL;DR; success :thumbsup:

You can check the status of the CI Pipeline logs here ; https://github.com/aztfmod/terratest/actions/runs/808283002

**Comment by HadwaAbdelhalem** [comment]
@gruntwork-io/gruntwork-terratest-terragrunt ready for your review

**Review by yorinasub17 — APPROVED** [review]
LGTM! Running a sanity check build on our pipeline as well.

**Comment by yorinasub17** [comment]
Build passed! Going to merge and release this!

**Pull request merged**
