### PR TITLE
instead of pre-populated token , ci will run with given token

### PR DESCRIPTION
**Pull request by polatengin**
CI pipeline will use given _PAT_ instead of pre-populated secret _GITHUB_TOKEN_

so, it'll have given permission(_s_) through the _PAT_ ([generate a PAT page](https://github.com/settings/tokens/new))

### CODE REVIEW

**Review by brikis98 — COMMENTED** [review]
Could you provide a bit more context on this PR?

**Comment by rguthriemsft** [comment]
Look good to me, @yorinasub17 @brikis98 this PR fixes issue with posting a comment from CI into the PR on gruntworks repo.

**Comment by brikis98** [comment]
@rguthriemsft I understand that, but without more context, it's not clear why the var is now called `PAT` instead of `GITHUB_TOKEN`. Is this some change in the env vars you're setting in your account or something else I can't see?

**Comment by polatengin** [comment]
> @rguthriemsft I understand that, but without more context, it's not clear why the var is now called `PAT` instead of `GITHUB_TOKEN`. Is this some change in the env vars you're setting in your account or something else I can't see?

pre-populated GITHUB_TOKEN has only read permission on _other_ repos and write permission to _owned_ repos of the account.

switching a _custom PAT_ allows users to write-back a comment on the _given PR_.

we have another PR to explain this workflow a bit better, you can find it here; https://github.com/gruntwork-io/terratest/blob/fa784715fa61efeae107ac50f08b5982cf567c6e/docs/_docs/04_community/contributing.md#validate-the-pull-request-for-azure-platform

**Review by brikis98 — APPROVED** [review]
Ah, makes sense. Thanks! Merging now.

**Review by brikis98 — APPROVED** [review]

**Comment by brikis98** [comment]
Oh, dammit. I clicked the "update branch" button to pull in the latest from `master`... And now our checks won't let me merge this PR, as I'm a "committer" on it, without approval from someone else. One sec, getting another approver :-D

**Review by infraredgirl — APPROVED** [review]

**Comment by brikis98** [comment]
Thanks @infraredgirl!

**Pull request merged**
