### PR TITLE
move logic for checking labels to a retry loop

### PR DESCRIPTION
**Pull request by brikis98**
Re-opening @robmorgan #147 so that, hopefully, CircleCI tests run automatically.

### CODE REVIEW

**Comment by brikis98** [comment]
lol, still nope!

**Comment by brikis98** [comment]
I guess CircleCI is only triggered by commits. Let me see if me doing a dummy commit will do the trick...

**Comment by brikis98** [comment]
And... I don't have write access to your fork @robmorgan, so that's out.

**Comment by brikis98** [comment]
Can you grant me write access to your fork temporarily?

**Comment by robmorgan** [comment]
Sure, one moment.

**Comment by robmorgan** [comment]
@brikis98 yeah, unfortunately, the new and old versions pass locally for me. I have a feeling its only on CircleCI, maybe especially in conjunction with the number of parallel tests that run at the same time. I never tried to run both AWS + GCP together locally.

**Comment by robmorgan** [comment]
Lets merge to `master` and see what happens.

**Comment by brikis98** [comment]
OK, merging!

**Comment by robmorgan** [comment]
@brikis98 I guess we're in business? https://circleci.com/gh/gruntwork-io/terratest/401

**Comment by brikis98** [comment]
Yup! Thank you for the fix 👍

**Pull request merged**
