### PR TITLE
Update golang version to 1.17

### PR DESCRIPTION
**Pull request by ZPascal**
Hi community, I've updated the [deprecated](https://github.com/gruntwork-io/terratest/issues/1037) old version of Golang to the current version.

### CODE REVIEW

**Comment by ZPascal** [comment]
Hi @ina-stoyanova @infraredgirl @marinalimeira @robmorgan, Is there a chance to get a review? Thx

**Comment by denis256** [comment]
Hi, with the go version update, I think should reformatted files using new rules - on this PR, after execution of `gofmt` from 1.17 changes on files appears, not sure if it should be done in this PR or separated.


Example:
```
$ cd test
$ ~/sdk/go1.17/bin/gofmt -w *.go
$ git status
        modified:   helm_basic_example_integration_test.go
        modified:   helm_basic_example_template_test.go
        modified:   kubernetes_basic_example_service_check_test.go
        modified:   kubernetes_basic_example_test.go
        modified:   kubernetes_hello_world_example_test.go
        modified:   kubernetes_rbac_example_test.go
$ git diff
...
@@ -1,3 +1,4 @@
+//go:build kubeall || kubernetes
 // +build kubeall kubernetes
+//go:build kubeall || helm
 // +build kubeall helm


```

https://go.dev/doc/go1.17#gofmt

**Comment by ZPascal** [comment]
@denis256 For my understanding, it's better to reformat the files in a separate PR. I can prepare a PR for that.

**Comment by yorinasub17** [comment]
Thanks for the contribution! There are two issues that need to be resolved before we can merge this in:

- Our circleci config needs to be updated to use go 1.17 - else, the build will fail (https://github.com/gruntwork-io/terratest/blob/master/.circleci/config.yml#L10)
- Once you update the circleci config, you will need to address @denis256 comment about go fmt because the precommit hooks will then fail next.

Alternatively, you can set the `go.mod` version to 1.16 to avoid both of the above for now.

**Comment by ZPascal** [comment]
@yorinasub17 Thanks for the clarification and information. I will update my PR.

**Comment by ZPascal** [comment]
@yorinasub17 Is there a possibility to test the modified circle ci configuration?

**Comment by yorinasub17** [comment]
Apologies for the delay! Just ran the build and looks like it failed on the precommit hook for `go fmt`, this time in the `modules` directory. Can you take a look at the list and format them? Thanks!

https://app.circleci.com/pipelines/github/gruntwork-io/terratest/842/workflows/f12868bb-d1ce-4d60-8823-304e75b307bb/jobs/6910

**Comment by yorinasub17** [comment]
Thanks for the update! I kicked off the build, and it was able to get further, but there was still one more regression that needs to be addressed. All references to go `1.16.3` in https://github.com/gruntwork-io/terratest/tree/master/modules/logger/parser/fixtures need to be updated to point to `1.17`.

**Review by yorinasub17 — APPROVED** [review]
Thanks for the updates! The rerun of the build passed, and this is almost ready to go. One final check we need to make is to make sure that this doesn't break our Azure testing. 

@HadwaAbdelhalem when you get the chance, can you run this through our Azure GitHub Action and report the results? Thanks!

**Comment by HadwaAbdelhalem** [comment]
@yorinasub17 Looks good to me I ran the [CI](https://github.com/HadwaAbdelhalem/terratest/runs/4985117501?check_suite_focus=true), the failure is due to subscription limits.

**Comment by yorinasub17** [comment]
@HadwaAbdelhalem Thanks for running!

Will merge this in now! @ZPascal thanks for the contribution and working through the long cycles!

**Pull request merged**
