### PR TITLE
fix: replace the deprecated logger.Logf and logger.Log for the new Logger

### LINKED ISSUE #1448: Use of deprecated logger.Logf instead of Logger
**Describe the bug**
Some modules still use the deprecated `logger.Logf` funtion that has less flexibility than the new `Logger`.

**To Reproduce**
1. Change the global logger
2. Use `k8s.GetKubernetesClientFromOptionsE`
3. The confgured global logger is not used and instead the log is written to stdout

```go
logger.Default = logger.New(NewTerraTestLogger())
k8s.GetKubernetesClientFromOptionsE(t, options)
```

**Expected behavior**
Logs like `Configuring Kubernetes client using config file...` should use the configured logger.

**Versions**
- Terratest version: `v0.47.1`
- Environment details (Ubuntu 20.04, Windows 10, etc.): All envs

### PR DESCRIPTION
**Pull request by seblaz**
## Description

Fixes #1448.

Replaces the deprecated `logger.Logf` and `logger.Log` for the new Logger.

- [x] Update the docs.
- [x] Run the relevant tests successfully, including pre-commit checks.
- [x] Ensure any 3rd party code adheres with our [license policy](https://www.notion.so/gruntwork/Gruntwork-licenses-and-open-source-usage-policy-f7dece1f780341c7b69c1763f22b1378) or delete this line if its not applicable.
- [ ] Include release notes. If this PR is backward incompatible, include a migration guide.

## Release Notes (draft)

Removed the use of the deprecated logger.Logf and logger.Log and use the new Logger instead.

### Migration Guide

Not required.

### CODE REVIEW

**Review by james03160927 — APPROVED** [review]
LGTM

**Comment by seblaz** [comment]
Hi  @denis256, do we need your review to merge?

**Comment by seblaz** [comment]
Actually, it's just that I can't do the merge. @james03160927 , can you merge the pr?

image

**Comment by seblaz** [comment]
@james03160927 @denis256 do you think we can merge the pr?

**Comment by james03160927** [comment]
Yeah let's merge it. Sorry for the delay. The failing test doesn't seem to be related to your PR.

**Pull request merged**
