### PR TITLE
Fix build error due to deleted module. Add pause_before to packer-basic-example. Shave other yaks.

### PR DESCRIPTION
**Pull request by brikis98**
This PR fixes multiple issues:

1. Fix a build failure where a module we rely on in CI was deleted.
1. Add `pause_before` to `packer-basic-example`. Without this, we sometimes get build failures such as:

    ```
    TestBuildPackerArtifactWithGit/ref-sha 2021-01-29T15:45:17Z logger.go:66: 1611935117,,ui,message,    amazon-ebs: Reading package lists...
    TestBuildPackerArtifactWithGit/ref-sha 2021-01-29T15:45:17Z logger.go:66: 1611935117,,ui,message,    amazon-ebs: Reading package lists...
    TestBuildPackerArtifactWithGit/ref-sha 2021-01-29T15:45:17Z logger.go:66: 1611935117,,ui,message,    amazon-ebs: Building dependency tree...
    TestBuildPackerArtifactWithGit/ref-sha 2021-01-29T15:45:17Z logger.go:66: 1611935117,,ui,message,    amazon-ebs: Reading state information...
    TestBuildPackerArtifactWithGit/ref-sha 2021-01-29T15:45:17Z logger.go:66: 1611935117,,ui,message,    amazon-ebs: Calculating upgrade...
    TestBuildPackerArtifactWithGit/ref-sha 2021-01-29T15:45:17Z logger.go:66: 1611935117,,ui,message,    amazon-ebs: The following packages have been kept back:
    TestBuildPackerArtifactWithGit/ref-sha 2021-01-29T15:45:17Z logger.go:66: 1611935117,,ui,message,    amazon-ebs:   linux-aws linux-headers-aws linux-image-aws
    TestBuildPackerArtifactWithGit/ref-sha 2021-01-29T15:45:18Z logger.go:66: 1611935118,,ui,message,    amazon-ebs: The following packages will be upgraded:
    TestBuildPackerArtifactWithGit/ref-sha 2021-01-29T15:45:18Z logger.go:66: 1611935118,,ui,message,    amazon-ebs:   sudo tzdata
    TestBuildPackerArtifactWithGit/ref-sha 2021-01-29T15:45:18Z logger.go:66: 1611935118,,ui,error,==> amazon-ebs: E: Could not open file /var/lib/apt/lists/archive.ubuntu.com_ubuntu_dists_xenial-backports_universe_i18n_Translation-en - open (2: No such file or directory)
    TestBuildPackerArtifactWithGit/ref-sha 2021-01-29T15:45:18Z logger.go:66: 1611935118,,ui,error,==> amazon-ebs: E: Could not open file /var/lib/apt/lists/archive.ubuntu.com_ubuntu_dists_xenial-backports_universe_binary-amd64_Packages - open (2: No such file or directory)
    TestBuildPackerArtifactWithGit/ref-sha 2021-01-29T15:45:18Z logger.go:66: 1611935118,,ui,message,    amazon-ebs: 2 upgraded%!!(MISSING)(PACKER_COMMA) 0 newly installed%!!(MISSING)(PACKER_COMMA) 0 to remove and 3 not upgraded.
    TestBuildPackerArtifactWithGit/ref-sha 2021-01-29T15:45:18Z logger.go:66: 1611935118,,ui,error,==> amazon-ebs: E: Could not open file /var/lib/apt/lists/archive.ubuntu.com_ubuntu_dists_xenial-backports_main_i18n_Translation-en - open (2: No such file or directory)
    TestBuildPackerArtifactWithGit/ref-sha 2021-01-29T15:45:18Z logger.go:66: 1611935118,,ui,error,==> amazon-ebs: E: Could not open file /var/lib/apt/lists/archive.ubuntu.com_ubuntu_dists_xenial-backports_main_binary-amd64_Packages - open (2: No such file or directory)
    TestBuildPackerArtifactWithGit/ref-sha 2021-01-29T15:45:18Z logger.go:66: 1611935118,,ui,error,==> amazon-ebs: E: Could not open file 
    ```

    I _think_ this is due to the issue where you run `apt` too soon after boot...
1. Update `gruntwork-installer` version to pick up a new version of `fetch` that fixes a bug with the `--branch` argument.
1. Pick instance types dynamically for Packer builds, rather than hard-coding `t2.micro`, as `t2.micro` isn't available in all regions.
1. Add more retries for yet more transient provider download issues.

### CODE REVIEW

**Comment by brikis98** [comment]
Build failed because we were relying on the `terraform-aws-ci` version of `gcp-helpers`, but these were moved to the `terraform-google-ci` repo.

**Comment by brikis98** [comment]
This is currently blocked due to https://github.com/gruntwork-io/fetch/issues/87.

**Comment by robmorgan** [comment]
FYI - https://github.com/gruntwork-io/fetch/issues/87 has been fixed and released.

**Comment by brikis98** [comment]
> FYI - [gruntwork-io/fetch#87](https://github.com/gruntwork-io/fetch/issues/87) has been fixed and released.

Indeed! I just released https://github.com/gruntwork-io/gruntwork-installer/releases/tag/v0.0.33 too, and now have updated this PR to use it to see if it fixes the build.

**Comment by brikis98** [comment]
Yay, tests passed!

**Review by infraredgirl — APPROVED** [review]
LGTM!

**Comment by brikis98** [comment]
Thanks for the review! Merging now.

**Comment by robmorgan** [comment]
Yay!

**Pull request merged**
