### PR TITLE
Upgrade Go version to 1.14

### PR DESCRIPTION
**Pull request by toshi0607**
Go1.14 has been released in February.
https://golang.org/doc/go1.14

And Go 1.15 as well about 2 weeks ago. That includes useful testing features. Let's update one by one!

### CODE REVIEW

**Comment by yorinasub17** [comment]
It looks like the error message for a request timeout has changed in go1.14, causing one of our tests to fail.

Can you update the following line in `TestRequestTimeout` in `modules/http-helper/http_helper_test.go`?

```
diff --git a/modules/http-helper/http_helper_test.go b/modules/http-helper/http_helper_test.go
index e787b05..9df2c21 100644
--- a/modules/http-helper/http_helper_test.go
+++ b/modules/http-helper/http_helper_test.go
@@ -103,7 +103,7 @@ func TestRequestTimeout(t *testing.T) {
        if err == nil {
                t.Error("handler didn't return a timeout error")
        }
-       if !strings.Contains(err.Error(), "request canceled") {
+       if !strings.Contains(err.Error(), "Client.Timeout") {
                t.Errorf("handler didn't return an expected error, got %q", err)
        }
 }
```

**Comment by toshi0607** [comment]
Thank you! I fixed the target error message. https://github.com/gruntwork-io/terratest/pull/585/commits/179a35c6a3a1af208d574c4a162f350c6e61c2b7

**Comment by yorinasub17** [comment]
Thanks! Just kicked off another build and if it passes, should be able to merge this in.

**Comment by toshi0607** [comment]
@yorinasub17 Thank you for rerunning CI! The second trial seems to be successful. Does this PR need additional action or is it ok to wait for merge?

**Comment by yorinasub17** [comment]
@toshi0607 Apologies, I had this open on a tab, but had to restart my computer and lost it. Will be merging this in shortly.

**Comment by toshi0607** [comment]
Thank you!!!

**Pull request merged**
