### PR TITLE
[Azure] Add sovereign cloud support for SQL

### LINKED ISSUE #860: [Azure] Add sovereign cloud support for SQL
The Base URI is incorrectly resolved for the SQL client, and should be fixed to read from the environment.

Addresses #811

### PR DESCRIPTION
**Pull request by davidkpiano**
This PR resolves the Base URI for the SQL module to support sovereign cloud.

Addresses #811, fixes #860

cc. @rguthriemsft

### CODE REVIEW

**Comment by hattan** [comment]
[Microsoft CI Bot] TL;DR; success :thumbsup:

You can check the status of the CI Pipeline logs here ; https://github.com/aztfmod/terratest/actions/runs/745237447

**Review by HadwaAbdelhalem — APPROVED** [review]
LGTM. @gruntwork-terratest-terragrunt ready for your review

**Comment by yorinasub17** [comment]
NOTE: Looks like there is a merge conflict now that we merged some of the other PRs.

**Review by HadwaAbdelhalem — APPROVED** [review]
LGMT, @yorinasub17 conflicts resolved. Ready for your review

**Comment by davidkpiano** [comment]
Superseded by #884

**Comment by davidkpiano** [comment]
Superseded by #884

**Pull request closed without merging**
