### PR TITLE
Rename gruntwork-cli to go-commons

### PR DESCRIPTION
**Pull request by yorinasub17**

### CODE REVIEW

**Review by brikis98 — APPROVED** [review]
LGTM

**Comment by yorinasub17** [comment]
Thanks for review. Will wait for build to finish before merging!

**Review by infraredgirl — APPROVED** [review]
Nice, the new name go-commons definitely makes more sense.

**Comment by yorinasub17** [comment]
Ok build passed except for known issue with GCP. Going to merge this in! Thanks for review!

**Pull request merged**
