### PR TITLE
Don't use deprecated flags

### PR DESCRIPTION
**Pull request by mastertinner**
`-force` is deprecated. `-auto-approve` should be used instead.

### CODE REVIEW

**Comment by mastertinner** [comment]
I did with varying results. I'm sorry but I'm not going to run these tests on my AWS account anymore. I ended up paying more than $15 just because they weren't cleaned up correctly and I had to click through all the regions and clean everything up manually.

If running these tests in my own AWS account is required to create pull requests here, I'd rather close it.

**Comment by mastertinner** [comment]
I'm not sure... But my charges were mostly in the EC2 area.

**Comment by mastertinner** [comment]
@brikis98, so should i close this PR?

**Comment by brikis98** [comment]
Thanks for the reminder. I think this PR is safe to merge and see if the tests pass. However, in general, we can't accept PRs that have not been tested. Thanks!

**Comment by brikis98** [comment]
Apologies for the delay. Had to update Terraform in the CI system and then work past an intermittent test failure. New release is here: https://github.com/gruntwork-io/terratest/releases/tag/v0.9.14

**Comment by mastertinner** [comment]
No worries! And thanks for merging and releasing!

**Pull request merged**
