### PR TITLE
Adding support for upgrade and rollback operation

### PR DESCRIPTION
**Pull request by Saurabh-16**
As of now helm module only support install and delete operations. Adding support for upgrade and rollback operations also.

### CODE REVIEW

**Comment by Saurabh-16** [comment]
> This looks good!
> 
> Can you add some tests? You can use [TestRemoteChartInstall](https://github.com/gruntwork-io/terratest/blob/master/modules/helm/install_test.go#L1) as a template. Or alternatively, you can add an example + integration test pair similar to https://github.com/gruntwork-io/terratest/tree/master/examples/helm-basic-example (maybe `helm-upgrade-example`?).

I have added 

> This looks good!
> 
> Can you add some tests? You can use [TestRemoteChartInstall](https://github.com/gruntwork-io/terratest/blob/master/modules/helm/install_test.go#L1) as a template. Or alternatively, you can add an example + integration test pair similar to https://github.com/gruntwork-io/terratest/tree/master/examples/helm-basic-example (maybe `helm-upgrade-example`?).

I added a file upgrade_test.go. It has one test case 'TestRemoteChartInstallAndUpgrade' to check for install and upgrade of release.

1) First I am installing a helm chart 'chartmuseum'
2) After successful Installation , I am setting repl icaCount to 2. ( https://github.com/Saurabh-16/terratest/blob/features/upgrade-rollback/modules/helm/upgrade_test.go#L70 )
3) I am upgrading the release again. (https://github.com/Saurabh-16/terratest/blob/features/upgrade-rollback/modules/helm/upgrade_test.go#L74)
4) Verifying desired no. of pods are created after upgrade. (	https://github.com/Saurabh-16/terratest/blob/features/upgrade-rollback/modules/helm/upgrade_test.go#L88 )
5) Verifying service is up post upgrade.

**Comment by Saurabh-16** [comment]
> This looks good!
> 
> Can you add some tests? You can use [TestRemoteChartInstall](https://github.com/gruntwork-io/terratest/blob/master/modules/helm/install_test.go#L1) as a template. Or alternatively, you can add an example + integration test pair similar to https://github.com/gruntwork-io/terratest/tree/master/examples/helm-basic-example (maybe `helm-upgrade-example`?).

I added a file upgrade_test.go. It has one test case 'TestRemoteChartInstallAndUpgrade' to check for install and upgrade of release.

First I am installing a helm chart 'chartmuseum'
After successful Installation , I am setting repl icaCount to 2. ( https://github.com/Saurabh-16/terratest/blob/features/upgrade-rollback/modules/helm/upgrade_test.go#L70 )
I am upgrading the release again. (https://github.com/Saurabh-16/terratest/blob/features/upgrade-rollback/modules/helm/upgrade_test.go#L74)
Verifying desired no. of pods are created after upgrade. (	https://github.com/Saurabh-16/terratest/blob/features/upgrade-rollback/modules/helm/upgrade_test.go#L88 )
Verifying service is up post upgrade.

**Comment by yorinasub17** [comment]
The new test looks good. Will kick off the build now.

**Comment by yorinasub17** [comment]
The build failed for an unrelated issue. Since the kubernetes and helm tests passed, I am comfortable merging this. Will merge + cut release now. Thanks for the contribution!

**Pull request merged**
