### PR TITLE
Feature/add azure network

### PR DESCRIPTION
**Pull request by MathieuBuisson**
Hi,

Following https://github.com/gruntwork-io/terratest/pull/333 , which has introduced Azure support, the present PR adds coverage for network-related resources in the azure module :

  - Virtual Networks
  - Subnets
  - Network Security Groups
  - Public IPs

This contains only get methods for now.  
If needed, methods to create and delete resources can be added in the future.

I opted to create a separate example module and a separate example test file from the existing one for Azure, because there are quite a few resources involved.  
If you prefer to "merge" this example (and its test) with the existing one for Azure, I'm open to change that.

To view the end of the output of running the `go test` against the example test `terraform_azure_network_example_test.go`, please refer to [this gist](https://gist.github.com/MathieuBuisson/696583a8e79f5bc4436c4872b3c6f240).

Issue link :  https://github.com/gruntwork-io/terratest/issues/89

Thanks.

### CODE REVIEW

**Comment by brikis98** [comment]
@MathieuBuisson Thanks for the PR! As Terratest has grown (we just passed 3,000 stars!), we've had to think more about what types of helper functions we want in the library to make sure it doesn't become so big as to be unusable. Please check out the updated [contribution guidelines](https://github.com/gruntwork-io/terratest/blob/master/CONTRIBUTING.md), especially the part about [infrastructure and validation helpers](https://github.com/gruntwork-io/terratest/blob/master/CONTRIBUTING.md#infrastructure-and-validation-helpers). These Azure helpers meet requirements for "platforms" and "creating infrastructure," but what about "complexity" (i.e., are these just direct wrappers around the Azure SDK or are you doing something more complicated) and "popularity" (i.e., is this something most Azure/Terratest users will need or is it a relatively esoteric use case)?

**Comment by faizan82** [comment]
> (i.e., is this something most Azure/Terratest users will need or is it a relatively esoteric use case)?

@brikis98 This would be a nice addition for azure. At present, I would need to wrap azure sdk with terratest to test the cases covered here. Would be good if we can have this feature as part of terratest package. 
Also as we add more features for different clouds, I believe this is bound to become big. Perhaps we need to then target terratest for different cloud platforms separately.

**Comment by brikis98** [comment]
Please see https://github.com/gruntwork-io/terratest/issues/89 for the status on Terratest with Azure. In particular, we're [starting some work](https://github.com/gruntwork-io/terratest/issues/89#issuecomment-650052374) around it, and when that work is done, we'll be able to come back to this PR!

**Comment by yorinasub17** [comment]
Thanks for the initial contribution, and apologies we never got around to working with you to get this merged.

As @brikis98 mentioned, we are working out a new contribution standard for Azure specifically and actively working on getting that finalized. In the process, we merged a few PRs that appear to overlap with this in functionality (e.g., https://github.com/gruntwork-io/terratest/pull/631).

We also have a few more PRs from the Microsoft team we plan on prioritizing before officially announcing our new Azure contribution guidelines.

Given that, we will be closing this PR out, but feel free to contribute any missing functions from the package that you identify after the announcement.

Thanks for your patience, and again apologies that we never were able to bring this to merge.

**Pull request closed without merging**
