### PR TITLE
Fix infinite loop in terraform errors

### PR DESCRIPTION
**Pull request by tmthrgd**
fmt.Sprintf invokes the Error method when formatting values, this was causing an infinite loop.

Fixes golang/go#42270 (wrongly opened against the go project)

### CODE REVIEW

**Review by brikis98 — APPROVED** [review]
Ah, good fix, thank you! I'll kick off tests now.

**Comment by brikis98** [comment]
Tests failed, but due to an unrelated build issue. Trying to resolve it here: https://github.com/gruntwork-io/terratest/pull/691

**Comment by brikis98** [comment]
https://github.com/gruntwork-io/terratest/pull/691 is now merged. Could you pull the latest from master? I can then kick off tests again.

**Comment by tmthrgd** [comment]
@brikis98 No worries, it’s definitely a subtle bug.

I’ve let GitHub update the branch so it should be a clean merge again.

**Comment by brikis98** [comment]
Thx! I'll kick off tests again.

**Comment by brikis98** [comment]
Hm, we're getting some odd test failures. I don't think they are related to this PR. I'm looking into it in https://github.com/gruntwork-io/terratest/pull/693.

**Comment by tmthrgd** [comment]
@brikis98 No rush, ping me when that’s sorted and I’ll rebase this PR for you.

**Comment by brikis98** [comment]
OK, https://github.com/gruntwork-io/terratest/pull/693 is now merged. Could you pull in the latest from master?

**Comment by tmthrgd** [comment]
@brikis98 Done.

**Comment by brikis98** [comment]
Tests passed! However, we've had another merge. Could you pull in the latest from `master` one more time, and then I can merge this PR. Thanks!

**Review by brikis98 — APPROVED** [review]
Thanks! Merging now.

**Comment by brikis98** [comment]
https://github.com/gruntwork-io/terratest/releases/tag/v0.30.19

**Pull request merged**
