### PR TITLE
Feature: Enable JSON parsing for getting TF config variables

### LINKED ISSUE #954: Terratest seems to not being able to parse HCL JSON files
First of all, thanks for this awesome project :)

I currently want to provide input configuration with HCL JSON files (`xyz.tfvars.json`) and get single variables via `GetVariableAsStringFromVarFile`.

```go
terraformOptions := terraform.WithDefaultRetryableErrors(t, &terraform.Options{
	TerraformDir: "../",
	VarFiles:     []string{"test.tfvars.json"},
})

project := terraform.GetVariableAsStringFromVarFile(t, "./test.tfvars.json", "project_id")
```

However, also when looking into the code, it seems like terratest only supports parsing of HCL (`.tfvars`) files for `GetVariableAsStringFromVarFile`. The error message when executing the test usually looks like

```
Error:          Received unexpected error:
                   test.tfvars.json:1,1-2: Argument or block definition required; An argument or block definition is required here.
```

### PR DESCRIPTION
**Pull request by rescDev**
Fixes #954 

This change enables the parsing of `tfvars.json` files for getting variables of the submitted TF config files. Uses the JSON parsing functionality provided by the package already used for HCL parsing.

### CODE REVIEW

**Review by brikis98 — APPROVED** [review]
LGTM, thank you! I'll kick off tests now.

**Comment by rescDev** [comment]
@brikis98 thanks for your review ! it seems like the tests failed, however those seem to be unrelated to my changes. Is there anything i can do or something that needs to be adjusted ?

**Review by brikis98 — APPROVED** [review]
There's one test failure and it seems unrelated; some intermittent thing that we may have already fixed in `master`. Merging now, thanks!

**Comment by bj-1795** [comment]
@brikis98 Could you please help me understand how can we pass tfvars.json in terraform options??

**Comment by rescDev** [comment]
@bj-1795 just use

```go
terraformOptions := terraform.WithDefaultRetryableErrors(t, &terraform.Options{
	TerraformDir: "<path-to-terraform-dir>",
	VarFiles:     []string{"test.tfvars.json"},
})
```

so you basically just use the already known `VarFiles`

**Pull request merged**
