### PR TITLE
feat: add AWS SSO support

### PR DESCRIPTION
**Pull request by thundering-herd**
Hej,
To support AWS SSO we need to Bump the AWS SDK which is providing
support recently.

Also we need to adjust our creation of sessions to include the `SharedConfigState` field. See
https://aws.amazon.com/blogs/developer/aws-sso-support-in-the-aws-sdk-for-go/ for more information.

Cheers!

### CODE REVIEW

**Review by yorinasub17 — DISMISSED** [review]
This LGTM. Thanks for your contribution! We will kick off a regression build, and if that passes, this can be merged in.

**Review by yorinasub17 — COMMENTED** [review]
Ah looks like our precommit checks failed. Can you run `go fmt` on `modules/aws/auth.go`?

**Comment by thundering-herd** [comment]
@yorinasub17 thanks for the hint. It is now fixed :)

**Comment by yorinasub17** [comment]
Sorry for the delay in replying here! This patch worked, but it broke our binary build pipeline because the updated aws-sdk-go version requires more resources to compile.

Can you apply this commit here? https://github.com/gruntwork-io/terratest/commit/1919b724ddc57ebe83b62e4dec811dc50cba0fda

With that change, we should be able to merge this in!

**Comment by thundering-herd** [comment]
Ok, sorry for the delay but I know cherry-picked the mentioned commit.

**Comment by fzipi360** [comment]
Would be awesome to have this, it is blocking us now!

**Comment by yorinasub17** [comment]
Apologies for the delay. Update LGTM! I am kicking off the build now and if it passes, we can merge this in.

**Review by yorinasub17 — APPROVED** [review]
Build passed! Merging now! Thanks for the contribution!

**Review by infraredgirl — APPROVED** [review]

**Comment by yorinasub17** [comment]
Thanks @infraredgirl ! Merging now.

**Pull request merged**
