### PR TITLE
Correctly show method in log message for HTTPDoWithValidationRetry

### PR DESCRIPTION
**Pull request by artem-nefedov**

### CODE REVIEW

**Comment by brikis98** [comment]
Tests failed due to https://github.com/gruntwork-io/terratest/pull/580. Let's get that merged first!

**Comment by brikis98** [comment]
OK, https://github.com/gruntwork-io/terratest/pull/580 is merged. Could you rebase and I can kick tests off again?

**Comment by artem-nefedov** [comment]
Done, please check

**Comment by brikis98** [comment]
Thanks! I'll kick off tests again shortly.

**Comment by brikis98** [comment]
One test failed due to an unrelated, intermittent issue, so I'm OK to merge. Thanks!

**Comment by brikis98** [comment]
https://github.com/gruntwork-io/terratest/releases/tag/v0.28.13

**Pull request merged**
