### PR TITLE
Fix issue 904

### PR DESCRIPTION
**Pull request by ApostolosBenisis**

### CODE REVIEW

**Review by brikis98 — DISMISSED** [review]
Good catch, thanks! I'll kick off tests now.

**Comment by brikis98** [comment]
Pre-commit hooks failed:

```
[INFO] Initializing environment for https://github.com/gruntwork-io/pre-commit.
goimports................................................................Failed
- hook id: goimports
- files were modified by this hook

modules/terraform/var-file.go
```

Please run `goimports`!

**Comment by ApostolosBenisis** [comment]
@brikis98 sorry for the inconvenience, hopefully now the Pre-commit hooks will not fail

Run goimports 
Rebased on latest master and pushed

**Comment by brikis98** [comment]
Great, thanks! I'll re-run tests now.

**Comment by brikis98** [comment]
Hm, I think CircleCi is having some sort of outage right now...

**Comment by ApostolosBenisis** [comment]
@brikis98 The [CircleCI Jobs queuing and slow UI loading incident ](https://status.circleci.com/incidents/4phwxjmdfs08) was resolved and the build-and-test workflow run successfully

**Review by brikis98 — APPROVED** [review]
Tests passed! Merging now.

**Comment by brikis98** [comment]
https://github.com/gruntwork-io/terratest/releases/tag/v0.35.1

**Pull request merged**
