### PR TITLE
init go mod

### PR DESCRIPTION
**Pull request by simon-ibars-cko**
Hello,
Following a [previous pr](https://github.com/gruntwork-io/terratest/pull/264) to support go module for terratest, few comments and feedbacks have been made. This up to date to master PR deal with them.

### CODE REVIEW

**Comment by robmorgan** [comment]
I triggered a build, but it looks like we'll have to update our test infrastructure to work with Go modules. Build in question: https://circleci.com/gh/gruntwork-io/terratest/2216

**Comment by simon-ibars-cko** [comment]
Yeah indeed, I see that your .circleci file is using a lot dep [here ](https://github.com/gruntwork-io/terratest/blob/e83e28e2c84396f4a1c6422412138865379a737f/.circleci/config.yml#L54)and [here ](https://github.com/gruntwork-io/terratest/blob/e83e28e2c84396f4a1c6422412138865379a737f/.circleci/config.yml#L61) on Gopkg file, which explains why the build is failing.
Circleci does provide an image for go use cases (with support of go module and cache management).
I would suggest using this image for the jobs “setup” and “test. What do you think?

**Comment by yorinasub17** [comment]
> I would suggest using this image for the jobs “setup” and “test. What do you think?

We have a few other tools that we need in addition to the setup and it would be a pretty big change to replace our image.

I am committed to making the requisite CircleCI changes in a separate branch within the next two weeks that you can then cherry pick over here. Sorry for the indirection, but it will be a lot easier to do this on a branch in terratest than the fork since that will autorun circleci.

For everyone waiting on this, thanks for your patience!

**Comment by yorinasub17** [comment]
Hi! I just finished the work for our CI configuration to integrate with go modules. I just confirmed the integration worked on the branch `pull-request-384`. Can you cherry pick the following two commits here so that they are actually included in this PR and we can get a green check mark here?

- 73ee38adc26587a6078be01c5b20d723329f2d86
- fb8134c77eed49de041a24e6c5a18bf7000f5ddb

After that, we will discuss internally how to coordinate the release and write up a migration guide, but you can expect to see this merged and released within a few weeks.

**Comment by simon-ibars-cko** [comment]
Hi @yorinasub17 
Those commits are now part of this PR, let me know if you need anything else
Thank you

**Comment by robmorgan** [comment]
I've triggered a build: https://circleci.com/gh/gruntwork-io/terratest/2362

**Comment by yorinasub17** [comment]
I just ruined the previous green check mark, but confirmed build is green. Will be going ahead with merge plans.

**Pull request merged**
